id: P001680
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3PD185
  title: དབུས་འགྱུར་གྱི་གདན་ས་ཆེན་པོ་སེ་ར་ཐེག་ཆེན་གླིང་གི་གདན་རབས་ངོ་མཚར་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    d752aad3d30f4b7493bd88da58f9bef7:
      image_group_id: I4PD2986
      title: ''
      volume_number: 1
      total_pages: 1102
      base_file: v001.txt
